name: Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Build
        run: |
          go build ./...

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-curl
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Export GOROOT
        shell: bash
        run: echo "GOROOT=$(go env GOROOT)" >> "$GITHUB_ENV"
      - name: Build
        shell: msys2 {0}
        run: |
          export PATH="$(cygpath -u "$GOROOT")/bin:$PATH"
          export CC=x86_64-w64-mingw32-gcc
          export CGO_ENABLED=1
          go build ./...

  build-windows-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd win-from-linux
          docker build -t go-curltest-cross .
      - name: Cross-compile for Windows
        run: |
          docker run --rm -v "$(pwd):/workspace/go-curltest" go-curltest-cross bash -c "
            source cross-vars.sh && 
            cd go-curltest &&
            git config --global --add safe.directory /workspace/go-curltest &&
            go build -v -o curltest.exe .
          "
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: curltest-windows
          path: curltest.exe
