name: Cross-compile Windows from Linux

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  cross-compile-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mingw-w64 \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libssl-dev \
            zlib1g-dev \
            wget \
            unzip

      - name: Set up curl for Windows
        run: |
          # Create working directory
          mkdir -p /tmp/curl-windows
          cd /tmp/curl-windows
          
          # Try to download prebuilt curl for Windows first
          CURL_VERSION="8.11.1_1"
          CURL_URL="https://curl.se/windows/dl-${CURL_VERSION}/curl-${CURL_VERSION}-win64-mingw.zip"
          
          echo "Attempting to download prebuilt curl for Windows..."
          if curl -L -f -o "curl-win64-mingw.zip" "$CURL_URL"; then
            echo "Downloaded prebuilt curl for Windows"
            unzip -q curl-win64-mingw.zip
            CURL_DIR=$(find . -maxdepth 1 -type d -name "curl-*" | head -1)
            echo "CURL_PREFIX=/tmp/curl-windows/$CURL_DIR" >> $GITHUB_ENV
          else
            echo "Failed to download prebuilt curl, building from source..."
            
            # Build curl from source for Windows
            CURL_SRC_VERSION="8.11.1"
            curl -L -o "curl-${CURL_SRC_VERSION}.tar.gz" "https://curl.se/download/curl-${CURL_SRC_VERSION}.tar.gz"
            tar -xzf "curl-${CURL_SRC_VERSION}.tar.gz"
            cd "curl-${CURL_SRC_VERSION}"
            
            # Install Windows SSL/crypto libraries
            sudo apt-get install -y mingw-w64-tools
            
            # Configure curl for Windows cross-compilation
            ./configure \
              --host=x86_64-w64-mingw32 \
              --prefix="/tmp/curl-windows/curl-win64" \
              --enable-static \
              --disable-shared \
              --without-ssl \
              --without-libssl-prefix \
              --disable-ldap \
              --disable-ldaps \
              --disable-rtsp \
              --disable-dict \
              --disable-telnet \
              --disable-tftp \
              --disable-pop3 \
              --disable-imap \
              --disable-smb \
              --disable-smtp \
              --disable-gopher \
              --disable-manual
            
            make -j$(nproc)
            make install
            
            echo "CURL_PREFIX=/tmp/curl-windows/curl-win64" >> $GITHUB_ENV
          fi

      - name: Cross-compile for Windows
        run: |
          echo "Using curl from: $CURL_PREFIX"
          
          # Verify curl installation
          ls -la "$CURL_PREFIX"
          if [ -d "$CURL_PREFIX/include" ]; then
            ls -la "$CURL_PREFIX/include"
          fi
          if [ -d "$CURL_PREFIX/lib" ]; then
            ls -la "$CURL_PREFIX/lib"
          fi
          
          # Set up cross-compilation environment
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export CGO_ENABLED=1
          export GOOS=windows
          export GOARCH=amd64
          
          # Set CGO flags
          export CGO_CFLAGS="-I${CURL_PREFIX}/include -DCURL_STATICLIB"
          
          # Set up libraries for static linking
          if [ -d "${CURL_PREFIX}/lib" ]; then
            export CGO_LDFLAGS="-L${CURL_PREFIX}/lib -lcurl -lws2_32 -lcrypt32 -luser32 -lkernel32"
          else
            export CGO_LDFLAGS="-lcurl -lws2_32 -lcrypt32 -luser32 -lkernel32"
          fi
          
          echo "Cross-compilation environment:"
          echo "  CC=$CC"
          echo "  CGO_ENABLED=$CGO_ENABLED"
          echo "  GOOS=$GOOS"
          echo "  GOARCH=$GOARCH"
          echo "  CGO_CFLAGS=$CGO_CFLAGS"
          echo "  CGO_LDFLAGS=$CGO_LDFLAGS"
          
          # Build the application
          echo "Building go-curltest for Windows..."
          go build -v -x -ldflags="-s -w" -o curltest.exe .
          
          # Verify the build
          ls -la curltest.exe
          file curltest.exe

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: curltest-windows-amd64
          path: curltest.exe